[build]
  base = "."
  publish = "dist/"
  functions = "netlify/functions"
  command = "npm run build"

[functions]
  included_files = ["ledger_crunch.csv", "ledger_stable.csv"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
