const fs = require('fs');
let content = fs.readFileSync('server.js', 'utf8');

const newCrunchPrompt = `prompt = \`
You are an expert AI Career Coach. Based on the following financial forecast generated by an application I built, draft a highly compelling, eye-catchy, yet professional direct email addressed to the CEOs or CTOs of top tier tech companies or banks (e.g., Jamie Dimon at JPMorgan Chase, Jane Fraser at Citi, or top Tech CEOs).

Subject: Executive Talent Pitch: Demonstrating Predictive Financial Engineering

I am Gandikota Lalitha Subramanyam, and I am applying for a high-level position (e.g., VP of Engineering, Chief Architect, or Head of Treasury Tech). To demonstrate my capability in building robust, predictive financial systems, I developed this core engine.

Even in a simulated 'cash crunch' scenario, my engine accurately models complex cash flow timing mismatches:
- Analysis Date: July 14, 2026
- Daily sales average: $\${avgSales.toFixed(2)}
- Daily overhead average: $\${avgOverhead.toFixed(2)}
- Net positive daily operating cash flow: ~$\${(avgSales - avgOverhead).toFixed(2)}
- Cash crunch start date: \${crunchDate}
- Predicted shortfall: $\${maxShortfall.toFixed(2)}

Make the email eye-catchy, engaging, and professional. Use formatting like bullet points or bold text to make it skimmable for a busy executive. Focus on how my ability to build such predictive financial logic translates to driving massive value at their company in a senior leadership role. Only return the text of the email. Sign it as "Gandikota Lalitha Subramanyam".
\`;`;

const newStablePrompt = `prompt = \`
You are an expert AI Career Coach. Based on the following financial forecast generated by an application I built, draft a highly compelling, eye-catchy, yet professional direct email addressed to the CEOs or CTOs of top tier tech companies or banks (e.g., Jamie Dimon at JPMorgan Chase, Jane Fraser at Citi, or top Tech CEOs).

Subject: Executive Talent Pitch: Demonstrating Predictive Financial Engineering

I am Gandikota Lalitha Subramanyam, and I am applying for a high-level position (e.g., VP of Engineering, Chief Architect, or Head of Treasury Tech). To demonstrate my capability in building robust, predictive financial systems, I developed this core engine.

In this 'stable growth' scenario, my engine models robust financial health and liquidity:
- Analysis Date: July 14, 2026
- Daily sales average: $\${avgSales.toFixed(2)}
- Daily overhead average: $\${avgOverhead.toFixed(2)}
- Net positive daily operating cash flow: ~$\${(avgSales - avgOverhead).toFixed(2)}
- Projected 7-day liquidity: $\${currentBal.toFixed(2)}

Make the email eye-catchy, engaging, and professional. Use formatting like bullet points or bold text to make it skimmable for a busy executive. Focus on how my ability to build such predictive financial logic translates to driving massive value at their company in a senior leadership role. Highlight my ability to build high-performance systems. Only return the text of the email. Sign it as "Gandikota Lalitha Subramanyam".
\`;`;

let firstMatch = true;
content = content.replace(/prompt = `[\s\S]*?`;/g, (match) => {
    if (firstMatch) {
        firstMatch = false;
        return newCrunchPrompt;
    } else {
        return newStablePrompt;
    }
});

fs.writeFileSync('server.js', content, 'utf8');
